### ISSUE TITLE
thanks!

### ISSUE THREAD

**Issue by Nukiloco** [night-glider/fun_coding#1]
thanks for the fun plugin!

also the only issue currently is that the slime appears blurry.

**Comment by night-glider** [comment]
Thanks!

Actually i know why it is happening.
It's because godot imports "slime_pet.png" with "filter" enabled. It's default behaviour.
You can manually turn this option off in the import menu.

But i don't know how to fix this default behaviour. Do you have any idea?

**Comment by Nukiloco** [comment]
Simply enough is to set the texture flag on the image to none. I think I figured out a way to do it, I will post a fix when I'm done with it.

**Comment by Nukiloco** [comment]
> Thanks!
> 
> Actually i know why it is happening. It's because godot imports "slime_pet.png" with "filter" enabled. It's default behaviour. You can manually turn this option off in the import menu.
> 
> But i don't know how to fix this default behaviour. Do you have any idea?

https://github.com/night-glider/fun_coding/pull/2

**Comment by Nukiloco** [comment]
> Thanks!
> 
> Actually i know why it is happening. It's because godot imports "slime_pet.png" with "filter" enabled. It's default behaviour. You can manually turn this option off in the import menu.
> 
> But i don't know how to fix this default behaviour. Do you have any idea?

Here's the PR for the updated pet script! https://github.com/night-glider/fun_coding/pull/4

**Comment by night-glider** [comment]
Thanks for PR, my friend!
