### ISSUE TITLE
Feature request: Throw pet

### ISSUE THREAD

**Issue by blaze-the-star** [night-glider/fun_coding#5]
I think you should be able to throw the pet with the mouse cursor.

**Comment by night-glider** [comment]
hm, maybe I should make separate PET addon for Godot?

**Comment by blaze-the-star** [comment]
Perhaps

**Comment by night-glider** [comment]
OK so this plugin was made for godot addon Jam 1. And result was... disappointing. 49 place(out of 60). I guess I'll abandon this project. Sorry
